export default {
  products: [
    {
      _id: '1',
      name: 'Nike Airmax',
      category: 'Shoes',
      image: '/images/product-1.jpg',
      price: 200000,
      brand: 'Nike',
      rating: 4.8,
      numberReviews: 10,
      countInStock: 6,
    },
    {
      _id: '2',
      name: 'New Balance Speed',
      category: 'Shoes',
      image: '/images/product-2.jpg',
      price: 340000,
      brand: 'New Balance',
      rating: 4.8,
      numberReviews: 132,
      countInStock: 63,
    }, {
      _id: '3',
      name: 'Adidas Sprint',
      category: 'Shoes',
      image: '/images/product-3.jpg',
      price: 250000,
      brand: 'Adidas',
      rating: 5,
      numberReviews: 424,
      countInStock: 61,
    }, {
      _id: '4',
      name: 'Miles and Co',
      category: 'Shoes',
      image: '/images/product-4.jpg',
      price: 180000,
      brand: 'Miles co',
      rating: 4.4,
      numberReviews: 15,
      countInStock: 62,
    }, {
      _id: '5',
      name: 'Puma Suede',
      category: 'Shoes',
      image: '/images/product-5.jpg',
      price: 300000,
      brand: 'Puma',
      rating: 4.83,
      numberReviews: 101,
      countInStock: 69,
    }, {
      _id: '6',
      name: 'Puma Runner',
      category: 'Shoes',
      image: '/images/product-6.jpg',
      price: 200000,
      brand: 'Puma',
      rating: 4.82,
      numberReviews: 102,
      countInStock: 61,
    },
  ],
};
